---
- fail: msg="Bailing out - this play requires 'socat_service_name'"
  when: socat_service_name is not defined

- fail: msg="Bailing out - this play requires 'socat_command'"
  when: socat_command is not defined

- name: Install socat
  become: true
  apt:
    state: present
    pkg: socat

- name: generate socat.service
  become: true
  template:
    src: socat.service.j2
    dest: "/etc/systemd/system/socat-{{socat_service_name}}.service"
    mode: 0644
  notify: 'installed socat'
