---

- name: Enable a systemd socat service
  become: true
  systemd:
    daemon_reload: yes
    state: restarted
    enabled: True
    name: "socat-{{ socat_service_name }}"
  listen: "installed socat"
