---

- name: Enable a systemd socat service
  become: true
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "socat-{{ socat_service_name }}"
  listen: "installed socat"
